audit_header: false
title: "Des Moines's Best Real Estate Training"
description: Timothy Schutte, a top Real Estate Agent in Des Moines, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/timothy-schutte-30100919746
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Products
    url: https://des-moines-real-estate-school.myshopify.com/password   
client:
  name: Timothy Schutte
  title:
  license_number:
  about_markdown: |
    Timothy has been in the real estate business since 2007. Starting in the business as the market went through the mortgage melt down has taught him a lot about the business. He has grown the business every year even as the market slowed.

    His team is a top selling real estate broker in the Des Moines Metro area. Having acheieved the EXIT Realty International Platinum awards in 2017, Gold in 2013, 2014, 2015, and 2016 and the Bronze award in his first six months of joining EXIT Realty's system.

    As an entreprenuer, Timothy opened his own real estate brokerage in November 2013 as he continued to build his real estate sales team and invest in what he believe, Real Estate.

    An active member in the Real Estate community, he served on the Board of Directors for the Des Moines Area Association of Realtors (DMAAR).

    Having grown up on a farm in northwest Iowa, Timothy understands the definition of work. He enjoys the challenge Real Estate brings him.
  market: Des Moines
  brand: EXIT Realty Capital City
  brokerage:
  address: 2936 104th Street Urbandale, IA 50322
  phone: 515-253-3948
  phone_type:
  phone2:
  phone2_type:
  email: timothy@solddesmoines.com
  url: https://sold.exitrealtycc.com/blog/

forms:
  sitekey: 6LfRQ6saAAAAAJmdKReafxqbmrSUK0jT3h2x9RP0

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how EXIT Realty Capital City can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ExitRealtyCapitalCity/
  linkedin_url: https://www.linkedin.com/company/exitrealtycapitalcity
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Des Moines Real Estate Podcast with Timothy Schutte'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Des Moines Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from EXIT Realty Capital City - your professional Des Moines Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Des Moines, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Timothy Schutte'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Des Moines Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#348597'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#348597'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
